spring.application.name=lms-backend

spring.datasource.url=jdbc:mysql://localhost:3306/lms
spring.datasource.username=root
spring.datasource.password=Akshaya@31807

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akshayadatla2007@gmail.com
spring.mail.password=wpxe ecim sban dapp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.jpa.defer-datasource-initialization=true

